# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatDoYouWant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatDoYouWant
    # SwiftLint
    pod 'SwiftLint'

    # RxSwift
    pod 'RxSwift', '6.5.0'

    # RxCocoa
    pod 'RxCocoa', '6.5.0'

  target 'WhatDoYouWantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhatDoYouWantUITests' do
    # Pods for testing
  end

end
